CREATE TABLE IF NOT EXISTS `acc_bank_imports` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(255) NOT NULL,
  `import_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `type` ENUM('OFX','CSV') NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;